[workspace]
authors = ["Leonardo Holtz <leo.holtz98@gmail.com>"]
channels = ["conda-forge"]
name = "point-cloud-visualizer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
scikit-learn = ">=1.7.2,<2"
fastapi = ">=0.122.0,<0.123"
uvicorn-standard = ">=0.38.0,<0.39"

[pypi-dependencies]
pypcd = { git = "https://github.com/isisim/pypcd.git" }
